<?php

/**
 * Implementation of hook_flag_default_flags().
 */
function cmi_rocketship_flag_default_flags() {
  $flags = array();
  // Exported flag: "Highest Priority".
  $flags['highest_priority'] = array (
    'content_type' => 'node',
    'title' => 'Highest Priority',
    'global' => '1',
    'types' => 
    array (
      0 => 'issue',
    ),
    'flag_short' => 'On fire!',
    'flag_long' => 'Set this issue as on fire!',
    'flag_message' => '',
    'unflag_short' => 'Throw water',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => '2',
      ),
      'unflag' => 
      array (
        0 => '2',
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}