<?php

/**
 * Implementation of hook_flag_default_flags().
 */
function cmi_rocketship_flag_default_flags() {
  $flags = array();
  // Exported flag: "Highest Priority".
  $flags['highest_priority'] = array (
    'content_type' => 'node',
    'title' => 'Highest Priority',
    'global' => '1',
    'types' => 
    array (
      0 => 'issue',
    ),
    'flag_short' => 'On fire!',
    'flag_long' => 'Set this issue as on fire!',
    'flag_message' => '',
    'unflag_short' => 'Throw water',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => '2',
      ),
      'unflag' => 
      array (
        0 => '2',
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}

/**
 * Implements hook_views_api().
 */
function cmi_rocketship_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'cmi_rocketship') . '/includes/views',
  );
}

/**
 * Implements hook_views_default_views().
 */
function cmi_rocketship_views_default_views() {
  // Search the "views" directory for files ending in .view.inc.
  $files = file_scan_directory(drupal_get_path('module', 'cmi_rocketship') . '/includes/views', '/view.inc$/');
  watchdog('rocketship', print_r($files, TRUE));
  foreach ($files as $absolute => $file) {
    // This is not require_once because it's possible that
    // hook_views_default_views() gets called more than once.
    require $absolute;
    if (isset($view)) {
      // $file->name has the ".inc" stripped off, but still has the ".view".
      $view_name = substr($file->name, 0, strrpos($file->name, '.'));
      $views[$view_name] = $view;
    }
  }
  return $views;
}

